Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true 

  ### Shared Box ###
  ubuntu_box = "ubuntu/bionic64"

  ### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = ubuntu_box
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"
  end

  ### Tomcat VM ###
  config.vm.define "app01" do |app01|
    app01.vm.box = ubuntu_box
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  ### RabbitMQ VM ###
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = ubuntu_box
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.16"
  end

  ### Memcache VM ###
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = ubuntu_box
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
  end

  ### DB VM ###
  config.vm.define "db01" do |db01|
    db01.vm.box = ubuntu_box
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
  end
end
