version: 0.2

env:
  parameter-store:
    CODEARTIFACT_AUTH_TOKEN: codeartifact-token

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using Corretto 17 with APT-installed Maven"
      - mkdir -p /root/.m2

      # Replace token in settings.xml at runtime
      - |
        sed "s|{{CODEARTIFACT_AUTH_TOKEN}}|$CODEARTIFACT_AUTH_TOKEN|g" ./settings.xml > /root/.m2/settings.xml

  pre_build:
    commands:
      - apt-get update -y
      - apt-get install -y jq maven

  build:
    commands:
      - echo "Starting Maven Build"
      - mvn clean install -DskipTests

artifacts:
  files:
    - target/**/*.war
  discard-paths: yes
