version: 0.2

env:
  parameter-store:
    LOGIN: sonartoken
    HOST: Host
    ORGANISATION: Organisation
    PROJECT: Project
    CODEARTIFACT_AUTH_TOKEN: codeartifact-token

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - mkdir -p /root/.m2
      - cp ./settings.xml /root/.m2/settings.xml
      - export MAVEN_VERSION=3.9.10  # Define Maven version

  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq
      - wget https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
      - tar xzvf apache-maven-${MAVEN_VERSION}-bin.tar.gz
      - ln -s apache-maven-${MAVEN_VERSION} maven
      - export PATH=$PWD/maven/bin:$PATH

  build:
    commands:
      - mvn clean install -DskipTests

artifacts:
  files:
    - target/**/*.war
  discard-paths: yes
