version: 0.2

env:
  parameter-store:
    CODEARTIFACT_AUTH_TOKEN: codeartifact-token

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using Corretto 17 with APT-installed Maven"
      - mkdir -p /root/.m2
      - |
        sed "s|{{CODEARTIFACT_AUTH_TOKEN}}|$CODEARTIFACT_AUTH_TOKEN|g" ./settings.xml > /root/.m2/settings.xml

  pre_build:
    commands:
      - apt-get update -y
      - apt-get install -y jq maven

  build:
    commands:
      - echo "Starting Maven Build"
      - mvn clean install -DskipTests
      - TIMESTAMP=$(date +%Y%m%d%H%M%S)
      - cp target/*.war target/vprofile-v2-$TIMESTAMP.war

artifacts:
  files:
    - target/vprofile-v2-*.war
  discard-paths: yes
